version: '3.8'
name: AgentFramework
services:
  postgres:
    image: postgres:17.6-alpine
    container_name: AgentFramework-PostgresSQL
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: agentframework
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: AgentFramework-Pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 5555
    ports:
      - "5555:5555"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:


networks:
  postgres_network:
    driver: bridge
